-- Criação da tabela Ufo
CREATE TABLE ufo (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location VARCHAR(255),
    color VARCHAR(255),
    shape VARCHAR(255),
    date_and_time TIMESTAMP,
    quantity INT
);